#!/bin/bash

_HOST="$1"

EXPIRYDATE=`echo "QUIT" | openssl s_client -servername $_HOST -connect $_HOST:443 2> /dev/null | openssl x509 -noout -enddate 2>/dev/null | sed 's/notAfter=//G'`

EXPIRYDATE_epoch=$(date --date "$EXPIRYDATE" +%s)

echo $EXPIRYDATE_epoch
